apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
components:
- ../../components/sidecars
images:
- name: registry.k8s.io/cloud-provider-ibm/ibm-powervs-block-csi-driver
  newTag: v0.13.1
  digest: sha256:b034c8407c1a36c628c7cdf13f7ac2776d10aff79c3a093658dafab07ed39031
