FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.14 AS builder
WORKDIR /go/src/github.com/openshift/ibm-powervs-block-csi-driver
COPY . .
RUN make driver node-update-controller

FROM registry.ci.openshift.org/ocp/4.14:base
COPY --from=builder /go/src/github.com/openshift/ibm-powervs-block-csi-driver/bin/ibm-powervs-block-csi-driver /bin/ibm-powervs-block-csi-driver
COPY --from=builder /go/src/github.com/openshift/ibm-powervs-block-csi-driver/bin/node-update-controller /bin/node-update-controller
RUN yum install -y util-linux nfs-utils e2fsprogs xfsprogs ca-certificates && yum clean all && rm -rf /var/cache/yum

LABEL description="IBM PowerVS Block CSI Driver"

ENTRYPOINT ["/bin/ibm-powervs-block-csi-driver"]
