FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.11 AS builder
WORKDIR /go/src/github.com/openshift/ibm-powervs-block-csi-driver
COPY . .
RUN make driver

FROM registry.ci.openshift.org/ocp/4.11:base
COPY --from=builder /go/src/github.com/openshift/ibm-powervs-block-csi-drivern/bin/ibm-powervs-block-csi-driver /bin/ibm-powervs-block-csi-driver
RUN yum install -y util-linux nfs-utils e2fsprogs xfsprogs ca-certificates && yum clean all && rm -rf /var/cache/yum

LABEL description="IBM PowerVS Block CSI Driver"

ENTRYPOINT ["/bin/ibm-powervs-block-csi-driver"]
