apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: main_image.yaml
- target:
    kind: DaemonSet
    name: powervs-csi-node
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --debug
- target:
    kind: Deployment
    name: powervs-csi-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --debug
