// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/device/device.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination=pkg/driver/mocks/device_mock.go -source ./pkg/device/device.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLinuxDevice is a mock of LinuxDevice interface.
type MockLinuxDevice struct {
	ctrl     *gomock.Controller
	recorder *MockLinuxDeviceMockRecorder
}

// MockLinuxDeviceMockRecorder is the mock recorder for MockLinuxDevice.
type MockLinuxDeviceMockRecorder struct {
	mock *MockLinuxDevice
}

// NewMockLinuxDevice creates a new mock instance.
func NewMockLinuxDevice(ctrl *gomock.Controller) *MockLinuxDevice {
	mock := &MockLinuxDevice{ctrl: ctrl}
	mock.recorder = &MockLinuxDeviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinuxDevice) EXPECT() *MockLinuxDeviceMockRecorder {
	return m.recorder
}

// CreateDevice mocks base method.
func (m *MockLinuxDevice) CreateDevice() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevice")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockLinuxDeviceMockRecorder) CreateDevice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockLinuxDevice)(nil).CreateDevice))
}

// DeleteDevice mocks base method.
func (m *MockLinuxDevice) DeleteDevice() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockLinuxDeviceMockRecorder) DeleteDevice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockLinuxDevice)(nil).DeleteDevice))
}

// GetMapper mocks base method.
func (m *MockLinuxDevice) GetMapper() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapper")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMapper indicates an expected call of GetMapper.
func (mr *MockLinuxDeviceMockRecorder) GetMapper() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapper", reflect.TypeOf((*MockLinuxDevice)(nil).GetMapper))
}

// Populate mocks base method.
func (m *MockLinuxDevice) Populate(arg0 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Populate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Populate indicates an expected call of Populate.
func (mr *MockLinuxDeviceMockRecorder) Populate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Populate", reflect.TypeOf((*MockLinuxDevice)(nil).Populate), arg0)
}
